trigger:
  - main

schedules:
  - cron: '0 0 1 * *'
    displayName: Monthly schedule
    branches:
      include:
        - main

variables:
  - group: Agents
  - group: Credentials

  - name: repositoryName
    value: 'gabriellando/vlmcsd'

pool:
  name: $(agent_pool)
  demands:
    - Agent.OS -equals Linux

workspace:
  clean: all

steps:
  - task: Docker@2
    displayName: Docker Build And Push
    inputs:
      containerRegistry: '$(docker_hub_sc)'
      repository: $(repositoryName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
