trigger:
  - main

schedules:
  - cron: '0 0 1 * *'
    displayName: Monthly schedule
    branches:
      include:
        - main

variables:
  - group: Agents
  - group: Credentials

  - name: repositoryName
    value: 'gabriellando/vlmcsd'

pool:
  name: $(agent_pool)
  demands:
    - Agent.OS -equals Linux

workspace:
  clean: all

steps:
  - bash: |
      # Remove "gabriellando/vlmcsd" and "alpine" from the list of images
      docker image ls gabriellando/vlmcsd -q | xargs -r docker rmi
      docker image ls alpine -q | xargs -r docker rmi
    displayName: 'Clear Docker images before build'

  - task: Docker@2
    displayName: Docker Build And Push
    inputs:
      containerRegistry: '$(docker_hub_sc)'
      repository: $(repositoryName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
        tags: 'latest'
      ${{ else }}:
        tags: 'dev'

  - bash: |
      # Remove "gabriellando/vlmcsd" and "alpine" from the list of images
      docker image ls gabriellando/vlmcsd -q | xargs -r docker rmi
      docker image ls alpine -q | xargs -r docker rmi
    displayName: 'Clear Docker images after build'
