trigger:
  - main

variables:
  - group: Agents
  - group: Credentials

  - name: repositoryName
    value: 'vlmcsd'

pool:
  name: $(agent_pool)
  demands:
    - Agent.OS -equals Linux

steps:
  - task: Docker@2
    inputs:
      containerRegistry: '$(docker_hub_sc)'
      repository: $(repositoryName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
